version: 1.0
app:
  maven:
    groupId: "QuickSec"
    artifactId: "QuickSec"
    version: "ee10"
    type: ear
  instances:
    min: 1
    max: 5
  endpoints: public
  resources:
    # The vCPU number for the application. If not set, it defaults to 1 vCPU. 
    # The max number of vCPU that can be requested is 14.
    cpu: 1
  systemProperties:
    - name: "com.sun.jndi.ldap.object.disableEndpointIdentification"
    - value: "true"
  env:
    - name: cert_defaultTrustStore
      value: | 
        -----BEGIN CERTIFICATE-----
        MIIF0jCCA7qgAwIBAgIUHrVXdkOWiwoYO96Tl23+O+DL2IMwDQYJKoZIhvcNAQEL
        BQAwIzEhMB8GA1UEAwwYbmVzdC1sZGFwLTEuZnlyZS5pYm0uY29tMB4XDTIzMDYx
        NjIwMzk1N1oXDTMzMDYxMzIwMzk1N1owIzEhMB8GA1UEAwwYbmVzdC1sZGFwLTEu
        ZnlyZS5pYm0uY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA4siW
        ae9zKIwYHH8DToHUDsWVk727Fvoddi0ySR0LtA/Cso/c7eGxpyL35MueBEWpyqE2
        HfBIoEzJhq8CPngMDXMoHj6xmM83EcE74Qir22WXY2CMKwJJr8DE+vYtpKDjJGND
        ytxEDz8Qqs2bkeqP/+u3YuZGFbrF08TVGhdDF8tMP/qSsV+MSnZiRS8fDqFEAO10
        aO/mdjraPoSzT1b9jNWkuct9cWpGfyf7nAe/Jd3zckBTHMmlpurjlGjFk56DpKGT
        UZPH8/HkIi727GmEGQSfD0UbHcamUtOaYeA1T+riKeT5Gnfyh0cGIq9pwxnxhuzT
        +GqGHUwFpLAx/0p9ZULeuNQQ42rWJ8pdslthAcwiu/TSS1+XufBYrRrS4no5uk63
        nGJoG7bhA2Jmdjn0PDmDvR2ySBAt4TkDCBd/4kKD42SRtULyz59nqZrIXPHgZ249
        KDlvrqOTT9RawAtEo2KIaDRM6Zun0IOmSQ3qvJyLeOMIxscWAPbPUg0S7kNZATNE
        G8ERHOyIYSB4pkeZCxKNaLX0LASh7mD8wcjHuATghV6l2+X9a2n22bF9/WVQXJO5
        njeDP+8urfGYP+DcEkHChryJFWMISwzWt3i4wPeDeCG/GOtqhnqTxX2nvlz+jQEB
        W5sOEej5mcGfYwMgi/QVZ1Sa3GpRTDcuZ0qIIcMCAwEAAaOB/TCB+jCB2AYDVR0R
        BIHQMIHNghhuZXN0LWxkYXAtMS5meXJlLmlibS5jb22CGG5lc3QtbGRhcC0yLmZ5
        cmUuaWJtLmNvbYIYbmVzdC1sZGFwLTMuZnlyZS5pYm0uY29tgixzdnQtb3Blbmxk
        YXAubmVzdC1vcGVubGRhcC5zdmMuY2x1c3Rlci5sb2NhbIIZbmVzdC1sZGFweC0x
        LmZ5cmUuaWJtLmNvbYIZbmVzdC1sZGFweC0yLmZ5cmUuaWJtLmNvbYIZbmVzdC1s
        ZGFweC0zLmZ5cmUuaWJtLmNvbTAdBgNVHQ4EFgQUtZKOhY/cu81hTLRxHR8dutDP
        AEswDQYJKoZIhvcNAQELBQADggIBAGW6b9nQn3DqzAWpRJqAnqJzgUcOZUizmHOu
        jRoPBqbmj7n3CqJp3GLlthAVqaf8YrhdOVdBo0Zx2x2pd805myDI1Y/VLJzSFT22
        sq+VmFTz6wUOCxLks9NXsyXo+eHnCAvSkYNFSrmBfYHwjALFiWS4sFre2T3vstrw
        RZenpNUnXMPYxRbu/EgGBjznOWH0WSKE6nQelYuio6YsW26VTxE2I9Cr80FGEq9X
        QXv6kdhzr/IT6BQzoM000XmT7nwjyMsDg5ACHnYoW0vWZmb9iNXT62RJX58xkwxN
        FEVgD+lyVKubu3kTPBAi3Em1yht/IRSOPnI1dDuczh2d/LeEmj1TN7E3Isd+6S4P
        i5qq6qBMbNecGkliYkNQL7xwaT2WK6Zcpps96Cq7RwHOQ+1MgJ2TRWTC6OQA2KST
        IDnbqfRY4cJ2eIloQ8A8trJt6Jp/4hcGUR0bPnX+KV91AsasJiJt1xecyKRZfldu
        GXN9iyDvo1PQhLcbIP5tBGTw3LC8xgAYynzLqarE2nad4o9JoqKNFeXIxyfLB97N
        WhN7LhC1y9xLDE75by15CG+YadmZ91Jir8seePoYoq9bvc9ZjZKpj69UjWMTGfrS
        4+EMv51NHTm5NE8sKTGaJA/ZrsMV6KUlx90oI8NaEpoba5Tkv9u4OAii9uYUFmC3
        kEjnZSWi
        -----END CERTIFICATE-----
